theme: jekyll-theme-cayman
title: "Módulo 1. Introducción a la Ciencia de Datos para Científicos Sociales"
description: "Diplomatura en Ciencias Sociales Computacionales y Humanidades Digitales - UNSAM"
